version: '3'

services:
  db:
    container_name: ${POSTGRES_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./containers/pgsql/dockerfile
    platform: linux/x86_64
    volumes:
      - ./data:/var/lib/postgresql/data
    expose:
      - ${POSTGRES_PORT}
    env_file:
      - .env
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'
    networks:
      django_network:
        ipv4_address: ${POSTGRES_ADDR}

  app:
    container_name: yumeji
    build:
      context: .
      dockerfile: ./containers/django/dockerfile
    volumes:
      - ./code:/code
      - ./logs/django:/log
    ports:
      - 8080:8000
    tty: true
    stdin_open: true
    privileged: true
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'
    networks:
      django_network:
        ipv4_address: ${DJANGO_ADDR}
#    image: app:django
    # command: python manage.py runserver 0.0.0.0:8000
networks:
  django_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}