FROM python:3.12-bookworm
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY ./containers/requirements.txt /code/
RUN apt-get update \
    && apt-get install -y default-libmysqlclient-dev build-essential \
    && pip install --upgrade pip \
    && pip install -r requirements.txt

COPY . /code/