FROM python:3.12-bookworm
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
RUN apt-get update && apt-get -y upgrade
RUN apt -y install postgresql-client
WORKDIR /code
COPY ./containers/django/requirements.txt /code/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
# RUN apt-get install -y supervisor
# COPY ./containers/django/supervisord.conf /etc/supervisor/supervisord.conf
# COPY ./containers/django/init.sh /tmp/
# RUN chmod +x /tmp/init.sh
