version: '3'

volumes:
  mysql_data:

services:
  db:
    container_name: db
    image: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django-db
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    container_name: yumeji
    build:
      context: .
      dockerfile: ./containers/dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./code:/code
      - ./logs/django:/logme
    ports:
      - 8080:8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://django:django@db:3306/django-db
